#!/usr/bin/env python3
"""Print a _data/publications.yml seeded from InspireHEP.

    python3 tools/seed_publications.py > _data/publications.yml

Queries InspireHEP for ePIC collaboration papers and writes the YAML the
graph builder reads, one commented entry per record.  Deliberately NOT part
of the build: the publication list stays curated by hand, and this is only a
convenience for refreshing it.  Collaborator papers that carry no ePIC
collaboration tag will not be found by the query -- add those by hand.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

API_ROOT = "https://inspirehep.net/api/literature"
USER_AGENT = (
    "epic-eic-website/1.0 (+https://github.com/eic/www.epic-eic.org; "
    "publication list seeding)"
)

HEADER = """\
# Generated by tools/seed_publications.py -- review before committing.
#
# See the comments in the checked-in _data/publications.yml for what these
# keys mean and why the EIC White Paper and Yellow Report are not listed.
threshold: %d

publications:"""


def current_threshold(default=5):
    """The threshold already in _data/publications.yml, if there is one.

    Regenerating the list should not quietly reset a value someone tuned.
    """
    config = Path(__file__).resolve().parent.parent / "_data" / "publications.yml"
    try:
        found = re.search(r"^threshold:\s*(\d+)", config.read_text(encoding="utf-8"), re.M)
    except OSError:
        return default
    return int(found.group(1)) if found else default


def fetch(query, size):
    url = "%s?%s" % (
        API_ROOT,
        urllib.parse.urlencode(
            {
                "q": query,
                "fields": "texkeys,titles,earliest_date,control_number",
                "sort": "mostrecent",
                "size": size,
            }
        ),
    )
    request = urllib.request.Request(
        url, headers={"User-Agent": USER_AGENT, "Accept": "application/json"}
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.loads(response.read().decode("utf-8"))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("-q", "--query", default="collaborations:ePIC",
                        help="InspireHEP search query (default: %(default)s)")
    parser.add_argument("-n", "--size", type=int, default=250,
                        help="maximum number of records to request")
    parser.add_argument("-t", "--threshold", type=int, default=current_threshold(),
                        help="value written to the `threshold` key "
                             "(default: whatever _data/publications.yml already uses)")
    args = parser.parse_args(argv)

    payload = fetch(args.query, args.size)
    hits = (payload.get("hits") or {}).get("hits") or []
    total = (payload.get("hits") or {}).get("total", len(hits))
    print("%d record(s) matched %r" % (total, args.query), file=sys.stderr)
    if total > len(hits):
        print("warning: only the first %d were returned; raise --size"
              % len(hits), file=sys.stderr)
    if not hits:
        print("warning: no records found -- check the query, e.g. "
              "collaborations:EPIC", file=sys.stderr)

    print(HEADER % args.threshold)
    for hit in hits:
        metadata = hit.get("metadata") or {}
        texkeys = metadata.get("texkeys") or []
        key = texkeys[0] if texkeys else str(metadata.get("control_number"))
        titles = metadata.get("titles") or []
        raw_title = titles[0].get("title") if titles else None
        title = " ".join((raw_title or "").split())
        year = (metadata.get("earliest_date") or "")[:4]
        print("  - key: %s" % key)
        print("    # %s %s" % (year or "????", title[:88]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
